name: Docker Image CI

on:
  push:
    branches: []
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: docker pull
      run: |
        docker pull hopetree/izone:latest
        docker pull registry.cn-shenzhen.aliyuncs.com/tendcode/izone:latest
        docker images
